travis:
  secure:
    BINSTAR_TOKEN: euXqi+sz102ZfbsjhEDKiyQNDRuQe/hCMSAD3DZkdv8bBcEyFDz809FrBg6TEBN0cvbqmNQcyt7/4XeSpAH5ld6rHAG9h9ShLz1YOCa2BsPeIzbNpTyuHF5YLPqmXU04hleR4oxfFoNDKzbdoil4eEaUpAiUXCaQqRijyK9zdoz1Og+rJS2yypyD0t86/zuyBmhMvlm7hXnALKulVAZB4qRxjPCm1htv7/ur5JjD9sIRkLlFTPNPC0bKTZxjJe1TH3Gj1pJhIFy9qvBVZZex09fl77RxUA6G2wvGCa0hENPoi3anx2POoXhQ3ZtODcMq+kNzdOXUnyBKX75vCq7WIxRtQrtc4oQLLV13ETjz48D493olsPG6V7+1VlFRGmrAkMhc4c08Qkuqy4HWc4Pjs8iOUz03JySEWfUgP1Ce8l9ssFo7s2h8CIwZQZuzQhnW4DX8vR6hNDy3cbhnASJY4U+fSNYc2gAlCBJFB07S+nR7zoaAmDWSKqb99vhMkejPFq+eV2VKCBuXNxJyxmENEkN1pjqrR2BKn5JK+bKE8FL6cEf0FncsNXWhO5Pwy9IjJWmle4dFldXdFXDqAB7Vb02Kemb0bQeu22zmqrvRslQjU6yFg8hnJBOmWZEoTdUM/b1Y9ELIavLz7sW3cmyTxOJk0UPZhSNOi/sHSL8KZXg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
