travis:
  secure:
    BINSTAR_TOKEN: PwQZ3WfBjmIJpNZ1THtoSxcFtD8fmdF5gsQyJCgXxZ8XRlOK7Ol31f6xHkawvWZV28SAX54tfMwvmazmUYB86p84fPoM75TtpVda+KS+OeUR92zLDRh5RxU4jagCuBD6Hfb1HVUiK+WJQKIlWcptht6F1Zw3BWdUiS4LkHQfUIORQgWNqVVcvPvnros1QE3dOXNkR1ZqlEUQunK5KZduTnquPRFBLmJc439B9Itxuo38O0ndNj3XIeA/RKvxZF6rWglj4h0JHAD+jCnb6ieFxtOO3XLZBw+Xj2LNc9UVwMBrdozR3a8ejChHoAaxw22rOMOv9atnIJhu4EeOda9FwiOyO+5SEs+z5AAo50hw1tqQJHcPcQV5iGoXTv+LU9gsvI8KsoI4EMeMX63/CsCCrVtZ+dAFhhJzbj7+ciNOV5pONb7KPs7wTrXh8q2Pp0I180gxEaCbYuSpuq+7SfWBJa5MYfF9Yl++f3boXX3O5wqyRPAFcuVUR2Sve7j8CAtVj9Y6bpYoCuHRAFrInPcqnKyBGSyoFrWmEmMUWr/hqpvHm54XzGwVYEiEqC7jY2z7OP7AWcBAbJD5x7XJMYGVeyH5UQFuM2Buq2iVsSjOW9jlqdYUYsRy9KvecvJXiN9M/e99geUMPCJGLVUz4uunvMd2YM3vId3LtGHGr5MNODA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
